config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :markets, only: [:index, :show]

  resources :vendors, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = ServiceFacade.new.markets
  end

  def show
    @market = ServiceFacade.new.market(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = ServiceFacade.new.vendor(params[:id])
    if search_params.present? && search_input.present?
      @markets = ServiceFacade.new.markets_search(search_input) 
    else
      flash[:error] = "Name or city can not be sent on their own. Please provide other parameters to search for markets"
    end
  end

  private
  def search_params
    (params[:name].present? || params[:city].present? || params[:state].present? ) && (params[:name]!="Name" || params[:city]!="City" || params[:state]!="State")
  end

  def search_input
    if params[:name]!="Name" && params[:city]!="City" && params[:state]!="State"
      "name=#{params[:name]}&state=#{params[:state]}&city=#{params[:city]}"
    elsif params[:name]!="Name" && params[:state]!="State"
      "name=#{params[:name]}&state=#{params[:state]}"
    elsif params[:name]!="Name" && params[:city]!="City"
      "name=#{params[:name]}&city=#{params[:city]}"
    elsif params[:state]!="State" && params[:city]!="City"
      "state=#{params[:state]}&city=#{params[:city]}"
    elsif params[:state]!="State"
      "state=#{params[:state]}"
    else
      nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div id="flash">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
}
</style>
</head>
<body>

<h1>Markets</h1>
<section class="markets">
  <table style="width:80%">
    <tr>
      <th style="background-color:grey; color: white;">Name</th>
      <th style="background-color:grey; color: white;">City</th>
      <th style="background-color:grey; color: white;">State</th>
      <th style="background-color:grey; color: white;"></th>
    </tr>
    <% @markets.each do |market| %>
      <tr>
        <div id="market-<%= market.id%>">
          <td><%= market.name %></td>
          <td><%= market.city %></td>
          <td><%= market.state %></td>
          <td><%= button_to "More info", href: market_path(market) %></td>
        </div>
      </tr>
    <% end %>
  </table>
</section>

</body>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1>

<section class="address">
  <h6><%= @market.address %></h6>
</section>

<section class="vendors">
  <% @market.vendors.each do |vendor| %>
    <div id="vendor-<%=vendor.id%>">
      <%= link_to "#{vendor.name}", vendor_path(vendor.id) %>
    </div>
  <% end %>
</section>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>

<section class="contact">
  <h3>Contact Info:</h3>
  <h4>Name: <%= @vendor.contact_name %></h4>
  <h4>Phone: <%= @vendor.contact_phone %></h4>
</section>

<h3>Credit Accepted?: <%=@vendor.credit%></h3>
<h4>Description: <%=@vendor.description%></h4>

<section class="search_markets">
  <h4>Search for Markets to add this vendor:</h4>
  <%= form_with url: vendor_path(@vendor.id), method: :get do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, value: "Name" %>
    <%= f.label :city %>
    <%= f.text_field :city, value: "City" %>
    <%= f.label :state %>
    <%= f.text_field :state, value: "State" %>

    <%=f.submit "Search" %>
  <% end %>
</section>

<% if @markets %>
  <section class="found_markets">
    <% @markets.each do |market|%>
      <div id="market-<%= market.id %>">
        <li><%= link_to "#{market.name}", market_path(market.id) %></li>
      </div>
    <% end %>
  </section>
<% end %>